$ProjectPath = Join-Path $PSScriptRoot "RevitCliClient.csproj"
$OutputPath = Join-Path $PSScriptRoot "publish"

$Aot = $args -contains "--aot"

Write-Host "Publishing Revit CLI Client..." -ForegroundColor Cyan

if ($Aot) {
    Write-Host "Mode: Native AOT" -ForegroundColor Yellow
    dotnet publish $ProjectPath `
      -c Release `
      -r win-x64 `
      -o $OutputPath
} else {
    Write-Host "Mode: Single-File (self-contained)" -ForegroundColor Yellow
    dotnet publish $ProjectPath `
      -c Release `
      -r win-x64 `
      --self-contained true `
      -p:PublishSingleFile=true `
      -p:IncludeNativeLibrariesForSelfExtract=true `
      -p:PublishAot=false `
      -o $OutputPath
}

if ($LASTEXITCODE -eq 0) {
    Write-Host "`nPublished successfully!" -ForegroundColor Green
    Write-Host "Output: $OutputPath" -ForegroundColor Green
    Write-Host "Executable: $OutputPath\RevitCliClient.exe" -ForegroundColor Green

    $ExePath = Join-Path $OutputPath "RevitCliClient.exe"
    if (Test-Path $ExePath) {
        $Size = (Get-Item $ExePath).Length / 1MB
        Write-Host "Size: $([math]::Round($Size, 2)) MB" -ForegroundColor Green
    }

    Write-Host "`nGenerating help-text.md..." -ForegroundColor Cyan
    $HelpMdPath = Join-Path $OutputPath "help-text.md"
    $HelpContent = & $ExePath --help 2>&1 | Out-String
    $MdContent = @"
# RevitCliClient Command Reference

> Auto-generated by publish script. Do not edit manually.

``````
$($HelpContent.Trim())
``````

"@
    Set-Content -Path $HelpMdPath -Value $MdContent -Encoding UTF8
    Write-Host "Generated: $HelpMdPath" -ForegroundColor Green
} else {
    Write-Host "`nPublish failed!" -ForegroundColor Red
    exit 1
}
