@echo off
echo Publishing Revit CLI Client...

set "SCRIPT_DIR=%~dp0"
set "OUTPUT_DIR=%SCRIPT_DIR%publish"

if "%1"=="--aot" (
    echo Mode: Native AOT
    dotnet publish ^
      "%SCRIPT_DIR%RevitCliClient.csproj" ^
      -c Release ^
      -r win-x64 ^
      -o "%OUTPUT_DIR%"
) else (
    echo Mode: Single-File ^(self-contained^)
    dotnet publish ^
      "%SCRIPT_DIR%RevitCliClient.csproj" ^
      -c Release ^
      -r win-x64 ^
      --self-contained true ^
      -p:PublishSingleFile=true ^
      -p:IncludeNativeLibrariesForSelfExtract=true ^
      -p:PublishAot=false ^
      -o "%OUTPUT_DIR%"
)

if %ERRORLEVEL% EQU 0 (
    echo.
    echo Published successfully!
    echo Output: %OUTPUT_DIR%
    echo Executable: %OUTPUT_DIR%\RevitCliClient.exe

    echo.
    echo Generating help-text.md...
    (
        echo # RevitCliClient Command Reference
        echo.
        echo ^> Auto-generated by publish script. Do not edit manually.
        echo.
        echo `````````
        "%OUTPUT_DIR%\RevitCliClient.exe" --help
        echo `````````
        echo.
    ) > "%OUTPUT_DIR%\help-text.md"
    echo Generated: %OUTPUT_DIR%\help-text.md
) else (
    echo.
    echo Publish failed!
    exit /b 1
)
